### ISSUE TITLE
Search bar default still white

### ISSUE THREAD

**Issue by diogenes500** [DM164/Dark-by-DM#39]
The search box at the top is still white. when you select/start typing in it it then goes to a dark color. It would be desirable to have this be dark by default.

**Comment by DM164** [comment]
Fixed in the latest update

**Comment by diogenes500** [comment]
I just uninstalled and reinstalled and the issue persists. The versions, 4.9.27 are the same. Is there something else that needs to be done?

**Comment by DM164** [comment]
The latest one should be 5.32.2

**Comment by diogenes500** [comment]
FYI, this is what I see when adding the extension in firefox. Newest here is 4.9.27
![DR_firefox](https://user-images.githubusercontent.com/38104391/107132561-50390380-689d-11eb-967d-d5c5cfbb65f5.png)

**Comment by DM164** [comment]
Oh, I'm sorry but this is not my style, I haven't coded this extension. In order to get support you'll have to visit their homepage or install one of my styles.
